### PR TITLE
support for figures in tables in typst

### LINKED ISSUE #151: Typst: support `plot_tt()`
I just came across your package while playing with the typst  format that quarto has just included. Seems to be best for typst tables i've come across... :)

I tried out some of your examples... the ones with the embedded figures dont work though :( The following line stops it... 
https://github.com/vincentarelbundock/tinytable/blob/53ef9b2b26f27c10e04b2c16a41979c31c17343a/R/plot_tt.R#L205

Any chance you'll add support for that?

### PR DESCRIPTION
**Pull request by aghaynes**
fixes #151

### CODE REVIEW

**Comment by aghaynes** [comment]
the repeating header stuff doesnt seem to work... i'll remove it so that the PR is only for the figure issue

**Comment by vincentarelbundock** [comment]
Oh wow, you weren't kidding when you said adding this was simple ;)

Yeah, I think we also want to think about what the best user interface would be for repeated headers. I don't want to add too many arguments to the function. I'm not sure yet, but `"multipage"` might make sense as a value in the `theme` argument.

**Comment by aghaynes** [comment]
yes, it could be that there is some conflict with a theme - the table didnt break and looked like it had overwritten the last line with the remaining data... in any case... let me know if you want me to make any other changes :)

**Comment by vincentarelbundock** [comment]
It works! Thanks a ton!

works!

**Comment by vincentarelbundock** [comment]
Merged to main. I added a thanks with your github username to NEWS and bumped the version number.

**Pull request merged**
