### PR TITLE
Add documentation for available options

### PR DESCRIPTION
**Pull request by kylebutts**
Hey Vincent,

I figured it would be helpful to document the options available to users. Feel free to yoink and put somewhere else in the documentation.

A few things I noticed:
1. `tt_output_default` shows up here an nowhere else; should it be `tinytable_print_output`? https://github.com/vincentarelbundock/tinytable/blob/ae37427b62c3ed165b88c73c74eff94ce48e288f/R/sanity.R#L57

2. These options all involve latex options and are formatted differently: `tinytable_save_pdf_clean`, `tinytable_save_pdf_engine`, `tinytable_theme_placement_latex_float`, `tinytable_siunitx_table-format`. Maybe could sync them with `tinytable_latex_clean_files`, `tinytable_latex_engine`, `tinytable_latex_placement_float`, `tinytable_latex_siunitx_format`? Also note the `-` in the siunitx which is against the convention

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Looks awesome! Thanks!

I removed the `tt_output_default` option from `main`. I think this was a leftover from internal testing. 

I agree that we should make the global option names more consistent. What I tried (and failed) to do was name all options with a prefix which corresponds to the `tinytable` function to which they are relevant.

But I think your categories probably make more sense

couple more things:

* `tinytable_grid_hlines` should probably be `tinytable_markdown_hlines`
* `quarto_disable_processing` also matters for PDF and Typst, so there should be a "general" category or somesuch.


Is there any way we can preserve backward  compabitibility? Maybe write a simple internal `get_option()` command?

**Comment by kylebutts** [comment]
I think I understand better now! At the bottom of this is the vignette updated. 

1. Thoughts on removing `tidytable_themes`? This feels footguny, e.g. I want to add my custom theme to the list of string choices and I do `options(tidytable_themes = list('simple' = theme_simple))`. Oops, all the themes are deleted. I think it would be easier to just do `theme_tt(theme = theme_simple)`. Note `tinytable_tt_theme` exists for setting default theme.

2. I was working on documenting options for `theme_tt()` but I can't seem to figure out how to add options for some things (e.g. `tinytable_theme_multipage_rowfoot`). Where in `theme_tt.R` would I read that value from?


---
# Available Options

Options can be set with `options()` and change the default behavior of
tinytable. You can either set them in a script (usually at the top) or
via `.Rprofile`. Note that you want to [be
cautious](https://rstats.wtf/r-startup.html) with putting things in
`.Rprofile` since they might make results not reproducible (e.g. if you
change `tinytable_format_digits` in `.Rprofile`, the table will be
formatted differently).

## Global options

There are a set of global options that you can change. See `?tt()` for
details. These are:

`tinytable_quarto_disable_processing`, `tinytable_html_mathjax`,
`tinytable_save_pdf_clean`, `tinytable_save_pdf_engine`.

## Default values for function arguments

The rest of the options are function specific and start with
`tinytable_X_` where X is `tt`/`format`/`print`/`theme`. See the
corresponding help documentation for the what the argument looks like.

### `tt()`

`tinytable_tt_digits`, `tinytable_tt_caption`, `tinytable_tt_notes`,
`tinytable_tt_width`, `tinytable_tt_theme`, `tinytable_tt_rownames`

### `format_tt()`

`tinytable_format_bool`, `tinytable_format_date`,
`tinytable_format_digits`, `tinytable_format_escape`,
`tinytable_format_fn`, `tinytable_format_markdown`,
`tinytable_format_num_fmt`, `tinytable_format_num_mark_big`,
`tinytable_format_num_mark_dec`, `tinytable_format_num_suffix`,
`tinytable_format_num_zero`, `tinytable_format_other`,
`tinytable_format_quarto`, `tinytable_format_replace`,
`tinytable_format_sprintf`

### `print.tinytable()`

`tinytable_print_output`

### `theme_tt()`

`tinytable_theme_hlines`, `tinytable_theme_float_placement`,
`tinytable_theme_horizontal_placement`, `tinytable_theme_resize_width`,
`tinytable_theme_resize_direction`, `tinytable_theme_multipage_rowhead`,
`tinytable_theme_multipage_rowfoot`, `tinytable_theme_tabular_style`,
`tinytable_theme_siunitx_format`

**Comment by vincentarelbundock** [comment]
Looks fantastic!

Yep, we should remove `tinytable_themes`

Some arguments do not have global options yet. For those, you'd need to add a `getOption()` to the function signature. 

This signature has it already: https://github.com/vincentarelbundock/tinytable/blob/main/R/theme_tt.R#L205

This signature doesn't have it yet: https://github.com/vincentarelbundock/tinytable/blob/main/R/theme_tt.R#L71

**Comment by kylebutts** [comment]
Great! Final thing re 'global options'. Do you prefer them to be called global options or `save` options? Technically they are `build_tt()` options, but that's internal. Which naming style do you prefer:

1. By the general category (in my mind this is "global option" and this changes the least things)
`tinytable_quarto_disable_processing`, `tinytable_html_mathjax`, `tinytable_pdf_clean`, `tinytable_pdf_engine`, `tinytable_markdown_hlines`

2. By `build` options (ppl don't know build but I think they would get "when building the table" do this thing?)
`tinytable_build_disable_quarto_processing`, `tinytable_build_html_mathjax`, `tinytable_build_pdf_clean`, `tinytable_build_pdf_engine`, `tinytable_build_markdown_hlines`

3. By `save` option (I don't think I like this b/c print uses these too)
`tinytable_save_disable_quarto_processing`, `tinytable_save_html_mathjax`, `tinytable_save_pdf_clean`, `tinytable_save_pdf_engine`, `tinytable_save_markdown_hlines`

**Comment by vincentarelbundock** [comment]
Hmmm, I think 1?

2 feels esoteric and internal

3 isn't consistent with the rest of our naming scheme, since they are not technically arguments of the `save_tt()` function.

What do you think?

**Comment by kylebutts** [comment]
I think I've come around to 1 too. That with the `global_options` documentation feels sufficient. I've given all the changes a once over and it looks cleaned up to me.

**Comment by vincentarelbundock** [comment]
This looks fantastic. Great contribution, thanks!

**Pull request merged**
